## Vendra Subscription

The `misaf/vendra-subscription` package owns billing **accounts**, **plans**, and **subscriptions** for the Vendra platform, plus the tenant-provisioning orchestration it started from. An `Account` owns many websites (the existing `Misaf\VendraTenant\Models\Tenant`, linked via `tenants.account_id`) and holds one active `Subscription` to a `Plan` that caps website count and defines a validity period.

### Standards

### Translatable Persistence

- Making a persisted model field translatable is an explicit domain choice unless this package already requires it.
- Every field listed in a model's `$translatable` array must definitely use a JSON database column. Keep its model traits/casts, factories, validation, Filament locale UI, API serialization, and tests translation-aware.
- A field not listed in `$translatable` must use the appropriate scalar database type and must not use Spatie Translatable, translatable slug traits, locale switchers, translated callbacks, or translation-shaped array data.

- Keep subscription code inside `packages/vendra-subscription` using the `Misaf\VendraSubscription` namespace.
- This package owns `Models\{Account,Plan,Subscription}`, `Enums\{PeriodUnit,SubscriptionStatus}`, `Support\WebsiteQuota`, `Exceptions\SubscriptionLimitException`, the actions (`CreateAccountAction`, `SubscribeAccountAction`, `ChargeSubscriptionAction`, `EnforceSubscriptionsAction`, `CreateTenantAction`, `ProvisionTenantAction`), the notifications, the console commands (`vendra-subscription:provision`, `vendra-subscription:enforce-subscriptions`), `Database\Seeders\PlanSeeder`, and `SubscriptionServiceProvider`.
- `Account` is the billing entity: `hasMany` tenants (websites) via `tenants.account_id`, `hasMany` subscriptions, `hasOne` `ownerUser` (a `User` via `users.account_id`), and holds owner contact fields. `activeSubscription()` returns the latest active, in-window subscription. Define the `Account → Tenant` relationship only on the `Account` side — never add an `account()` relation to `Tenant`, to avoid a `vendra-tenant → vendra-subscription` cycle.
- Keep one active subscription per account: `SubscribeAccountAction` cancels any active subscription before creating the new one, snapshots the plan's `price`/`currency_code` onto the subscription, applies a trial (`trial_ends_at`) only on the account's first subscription, and reactivates suspended websites. It throws `SubscriptionLimitException::planBelowUsage` when a plan cannot hold the account's current websites (downgrade guard).
- Enforce quotas through `Support\WebsiteQuota` (active subscription + `max_websites`); enforce the lifecycle through `EnforceSubscriptionsAction` (expire lapsed subscriptions, send expiry reminders once, suspend websites past `ends_at`+`grace_days`). Cascade offboarding lives in `Account::booted()` (`deleting` soft-deletes websites + domains and cancels the subscription).
- Do payment collection through the `Misaf\VendraSupport\Contracts\SubscriptionCharger` capability contract only — never depend on `misaf/vendra-transaction` here. `ChargeSubscriptionAction` resolves the charger and the account owner and skips free plans, trials, missing owners, and unavailable providers. The host app binds the real charger.
- This module intentionally references the tenant provider (`Misaf\VendraTenant\Models\{Tenant,TenantDomain}`) and composes other modules' actions (e.g. `Misaf\VendraPermission\Actions\CreateRoleAction`); keep that coupling in provisioning/subscription code and explicit in `composer.json`. Platform/account Filament panels and resources are app-level, not in this package.
- Owner-facing mail notifications are plain (synchronous), not `ShouldQueue`: queued notifications crash on the sync test queue via Spatie's tenant-aware-job wrapper. For async delivery, wrap sends in a `NotTenantAware` job (see `Misaf\VendraTenant\Jobs\CacheTenantRoutesJob`).
- `vendra-subscription:provision` is idempotent only with `--if-missing`; `--account`/`--plan` attach the website to an existing account or create one subscribed to a plan. Wrap multi-step work in `DB::transaction`, emit `Misaf\VendraSupport\Events\TenantProvisioned`, and keep artisan-driven steps (route caching) idempotent with failures surfaced.
- Account/Plan/Subscription implement `Misaf\VendraSupport\Contracts\ShouldLogActivity` (marker only). New plan/subscription columns must be reflected in the root `database/migrations` baseline byte-identically to the package `.stub` (enforced by `FreshDatabaseSchemaTest`, which also forbids `add_/rename_` follow-up migrations); cross-table references use plain indexed columns, no DB foreign keys.
- Follow Laravel comment style: document with PHPDoc (array shapes, generics, `@see`) and reserve inline comments for genuinely complex logic.
- Keep tests purposeful: cover quota/downgrade guards, lifecycle transitions, charging (via a fake `SubscriptionCharger`), provisioning rollback, and emitted events — not framework internals.
- Keep Pest architecture tests in `tests/ArchTest.php`: the `php`, `security`, and `laravel` presets. As a tenant-coupled module it does not assert a `not->toUse('Misaf\VendraTenant')` expectation.
